#server:
#  port: 11000
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gulimall_pms?characterEncoding=utf-8&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.8.250:8848
#  application:
#    name: gulimall-product
#mybatis-plus:
#  mapper-location: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

