server:
  port: 10000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gulimall_oms?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.250:8848
  application:
    name: gulimall-order
mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
