#server:
#  port: 13000
#
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.8.250:8848
#  application:
#    name: gulimall-gateway

##  springcloud-gateway 文档
##  https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/
spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu

        - id: test_route1
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        ## 前端项目 发送请求都带上 /api 前缀
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: third_part_product_route
          uri: lb://gulimall-third-part
          predicates:
            - Path=/api/thirdparty/oss/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}